/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    'map-markers': MapMarker;
    users: User;
    media: Media;
    posts: Post;
    'posts-categories': PostsCategory;
    'posts-tags': PostsTag;
    pages: Page;
    roles: Role;
    'gallery-albums': GalleryAlbum;
    'gallery-images': GalleryImage;
    'gallery-tags': GalleryTag;
    'gallery-categories': GalleryCategory;
    gardens: Garden;
    kits: Kit;
    scales: Scale;
    manufacturers: Manufacturer;
    'models-tags': ModelsTag;
    models: Model;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    search: Search;
    'api-keys': ApiKey;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
    'payload-query-presets': PayloadQueryPreset;
  };
  collectionsJoins: {
    media: {
      relatedPosts: 'posts';
    };
    'gallery-albums': {
      images: 'gallery-images';
    };
    kits: {
      models: 'models';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    'map-markers': MapMarkersSelect<false> | MapMarkersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'posts-categories': PostsCategoriesSelect<false> | PostsCategoriesSelect<true>;
    'posts-tags': PostsTagsSelect<false> | PostsTagsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'gallery-albums': GalleryAlbumsSelect<false> | GalleryAlbumsSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    'gallery-tags': GalleryTagsSelect<false> | GalleryTagsSelect<true>;
    'gallery-categories': GalleryCategoriesSelect<false> | GalleryCategoriesSelect<true>;
    gardens: GardensSelect<false> | GardensSelect<true>;
    kits: KitsSelect<false> | KitsSelect<true>;
    scales: ScalesSelect<false> | ScalesSelect<true>;
    manufacturers: ManufacturersSelect<false> | ManufacturersSelect<true>;
    'models-tags': ModelsTagsSelect<false> | ModelsTagsSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    'payload-query-presets': PayloadQueryPresetsSelect<false> | PayloadQueryPresetsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-meta': SiteMeta;
    'site-navigation': SiteNavigation;
    webhooks: Webhook;
  };
  globalsSelect: {
    'site-meta': SiteMetaSelect<false> | SiteMetaSelect<true>;
    'site-navigation': SiteNavigationSelect<false> | SiteNavigationSelect<true>;
    webhooks: WebhooksSelect<false> | WebhooksSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (PayloadMcpApiKey & {
        collection: 'payload-mcp-api-keys';
      });
  jobs: {
    tasks: {
      sendWelcomeEmail: TaskSendWelcomeEmail;
      generateImageEXIF: TaskGenerateImageEXIF;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Map markers, used for plotting points of interest
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-markers".
 */
export interface MapMarker {
  id: number;
  title: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location: [number, number];
  visits?: number | null;
  rating?: number | null;
  links?:
    | {
        title: string;
        album?: {
          relationTo: 'gallery-albums';
          value: number | GalleryAlbum;
        } | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Listing of all photo albums
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums".
 */
export interface GalleryAlbum {
  id: number;
  slug?: string | null;
  slugLock?: boolean | null;
  settings: {
    isNsfw?: boolean | null;
    category?: (number | null) | GalleryCategory;
    tags?: (number | GalleryTag)[] | null;
    visibility: 'ALL' | 'AUTHENTICATED' | 'PRIVILEGED';
    allowedRoles?: (number | Role)[] | null;
    allowedUsers?: (number | User)[] | null;
  };
  tracking?: {
    views?: number | null;
    downloads?: number | null;
    likes?: number | null;
    dislikes?: number | null;
    comments?: number | null;
    shares?: number | null;
    totalImages?: number | null;
  };
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?: {
    docs?: (number | GalleryImage)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Gallery categories.  Primary method of filtering galleries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories".
 */
export interface GalleryCategory {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gallery tags.  Used for more focused classification of gallery images.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-tags".
 */
export interface GalleryTag {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User roles and permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  description?: string | null;
  isDefault?: boolean | null;
  permissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User accounts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: (number | Role)[];
  displayName?: string | null;
  showNSFW?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Image
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  settings: {
    isNsfw?: boolean | null;
    'gallery-tags'?: (number | GalleryTag)[] | null;
    visibility: 'ALL' | 'AUTHENTICATED' | 'PRIVILEGED';
    allowedRoles?: (number | Role)[] | null;
    allowedUsers?: (number | User)[] | null;
  };
  exif?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  blurhash?: string | null;
  tracking?: {
    views?: number | null;
    downloads?: number | null;
    likes?: number | null;
    dislikes?: number | null;
    comments?: number | null;
    shares?: number | null;
  };
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  albums?: (number | GalleryAlbum)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | GalleryImage;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Media Items, images and otherwise
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  exif?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  blurhash?: string | null;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedPosts?: {
    docs?: {
      relationTo?: 'posts';
      value: number | Post;
    }[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Blog Posts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  originalPublicationDate?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  word_count?: number | null;
  category?: (number | null) | PostsCategory;
  tags?: (number | PostsTag)[] | null;
  relatedPosts?: (number | Post)[] | null;
  title: string;
  featuredImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Blog categories.  Used for general classification of blog posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts-categories".
 */
export interface PostsCategory {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog tags.  Used for more focused classification of blog posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts-tags".
 */
export interface PostsTag {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Singular dynamic page of the front end
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  visibility?: ('ALL' | 'AUTHENTICATED' | 'ANONYMOUS' | 'PRIVILEGED') | null;
  allowedRoles?: (number | Role)[] | null;
  blocks?:
    | {
        block?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Other things that don't have a spcecific home
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gardens".
 */
export interface Garden {
  id: number;
  slug?: string | null;
  slugLock?: boolean | null;
  name: string;
  featuredImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Model Kits
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kits".
 */
export interface Kit {
  id: number;
  full_title: string;
  title: string;
  kit_number: string;
  year_released: number;
  scalemates?: string | null;
  models?: {
    docs?: (number | Model)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  manufacturer: number | Manufacturer;
  scale: number | Scale;
  boxart?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * A built model, not to be confused with a kit
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  /**
   * Select a Clockify Project from your workspace
   */
  clockify_project?: string | null;
  model_meta: {
    featuredImage: number | Media;
    status: 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED';
    completionDate?: string | null;
    kit: number | Kit;
    tags?: (number | ModelsTag)[] | null;
    videos?:
      | {
          title: string;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  relatedResources?: {
    relatedPosts?: (number | Post)[] | null;
    relatedModels?: (number | Model)[] | null;
  };
  buildLog?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  image?: (number | Media)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Models tags.  Used for more focused classification of models.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models-tags".
 */
export interface ModelsTag {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Model kit manufacturers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers".
 */
export interface Manufacturer {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Model kit scales
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scales".
 */
export interface Scale {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  models?: {
    /**
     * Allow clients to find models.
     */
    find?: boolean | null;
    /**
     * Allow clients to create models.
     */
    create?: boolean | null;
    /**
     * Allow clients to update models.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete models.
     */
    delete?: boolean | null;
  };
  galleryAlbums?: {
    /**
     * Allow clients to find gallery-albums.
     */
    find?: boolean | null;
    /**
     * Allow clients to create gallery-albums.
     */
    create?: boolean | null;
    /**
     * Allow clients to update gallery-albums.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete gallery-albums.
     */
    delete?: boolean | null;
  };
  galleryImages?: {
    /**
     * Allow clients to find gallery-images.
     */
    find?: boolean | null;
    /**
     * Allow clients to create gallery-images.
     */
    create?: boolean | null;
    /**
     * Allow clients to update gallery-images.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete gallery-images.
     */
    delete?: boolean | null;
  };
  galleryTags?: {
    /**
     * Allow clients to find gallery-tags.
     */
    find?: boolean | null;
    /**
     * Allow clients to create gallery-tags.
     */
    create?: boolean | null;
    /**
     * Allow clients to update gallery-tags.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete gallery-tags.
     */
    delete?: boolean | null;
  };
  galleryCategories?: {
    /**
     * Allow clients to find gallery-categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create gallery-categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update gallery-categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete gallery-categories.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  gardens?: {
    /**
     * Allow clients to find gardens.
     */
    find?: boolean | null;
    /**
     * Allow clients to create gardens.
     */
    create?: boolean | null;
    /**
     * Allow clients to update gardens.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete gardens.
     */
    delete?: boolean | null;
  };
  kits?: {
    /**
     * Allow clients to find kits.
     */
    find?: boolean | null;
    /**
     * Allow clients to create kits.
     */
    create?: boolean | null;
    /**
     * Allow clients to update kits.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete kits.
     */
    delete?: boolean | null;
  };
  scales?: {
    /**
     * Allow clients to find scales.
     */
    find?: boolean | null;
    /**
     * Allow clients to create scales.
     */
    create?: boolean | null;
    /**
     * Allow clients to update scales.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete scales.
     */
    delete?: boolean | null;
  };
  manufacturers?: {
    /**
     * Allow clients to find manufacturers.
     */
    find?: boolean | null;
    /**
     * Allow clients to create manufacturers.
     */
    create?: boolean | null;
    /**
     * Allow clients to update manufacturers.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete manufacturers.
     */
    delete?: boolean | null;
  };
  modelsTags?: {
    /**
     * Allow clients to find models-tags.
     */
    find?: boolean | null;
    /**
     * Allow clients to create models-tags.
     */
    create?: boolean | null;
    /**
     * Allow clients to update models-tags.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete models-tags.
     */
    delete?: boolean | null;
  };
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update posts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete posts.
     */
    delete?: boolean | null;
  };
  postsCategories?: {
    /**
     * Allow clients to find posts-categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create posts-categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update posts-categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete posts-categories.
     */
    delete?: boolean | null;
  };
  postsTags?: {
    /**
     * Allow clients to find posts-tags.
     */
    find?: boolean | null;
    /**
     * Allow clients to create posts-tags.
     */
    create?: boolean | null;
    /**
     * Allow clients to update posts-tags.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete posts-tags.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  mapMarkers?: {
    /**
     * Allow clients to find map-markers.
     */
    find?: boolean | null;
    /**
     * Allow clients to create map-markers.
     */
    create?: boolean | null;
    /**
     * Allow clients to update map-markers.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete map-markers.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'models';
        value: number | Model;
      }
    | {
        relationTo: 'gardens';
        value: number | Garden;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage API keys for webhook stream authentication.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  /**
   * The user this API key belongs to
   */
  user: number | User;
  /**
   * The API key value. Keep this secret!
   */
  key: string;
  /**
   * Disable this to temporarily deactivate the API key without deleting it
   */
  active?: boolean | null;
  /**
   * Last time this API key was used
   */
  lastUsed?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendWelcomeEmail' | 'generateImageEXIF' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendWelcomeEmail' | 'generateImageEXIF' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'map-markers';
        value: number | MapMarker;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'posts-categories';
        value: number | PostsCategory;
      } | null)
    | ({
        relationTo: 'posts-tags';
        value: number | PostsTag;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'gallery-albums';
        value: number | GalleryAlbum;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'gallery-tags';
        value: number | GalleryTag;
      } | null)
    | ({
        relationTo: 'gallery-categories';
        value: number | GalleryCategory;
      } | null)
    | ({
        relationTo: 'gardens';
        value: number | Garden;
      } | null)
    | ({
        relationTo: 'kits';
        value: number | Kit;
      } | null)
    | ({
        relationTo: 'scales';
        value: number | Scale;
      } | null)
    | ({
        relationTo: 'manufacturers';
        value: number | Manufacturer;
      } | null)
    | ({
        relationTo: 'models-tags';
        value: number | ModelsTag;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets".
 */
export interface PayloadQueryPreset {
  id: number;
  title: string;
  isShared?: boolean | null;
  access?: {
    read?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (number | User)[] | null;
    };
    update?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (number | User)[] | null;
    };
    delete?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (number | User)[] | null;
    };
  };
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  columns?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  groupBy?: string | null;
  relatedCollection: 'posts' | 'kits' | 'models';
  /**
   * This is a temporary field used to determine if updating the preset would remove the user's access to it. When `true`, this record will be deleted after running the preset's `validate` function.
   */
  isTemp?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-markers_select".
 */
export interface MapMarkersSelect<T extends boolean = true> {
  title?: T;
  location?: T;
  visits?: T;
  rating?: T;
  links?:
    | T
    | {
        title?: T;
        album?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  displayName?: T;
  showNSFW?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  exif?: T;
  blurhash?: T;
  alt?: T;
  caption?: T;
  relatedPosts?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  originalPublicationDate?: T;
  slug?: T;
  slugLock?: T;
  word_count?: T;
  category?: T;
  tags?: T;
  relatedPosts?: T;
  title?: T;
  featuredImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts-categories_select".
 */
export interface PostsCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts-tags_select".
 */
export interface PostsTagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  visibility?: T;
  allowedRoles?: T;
  blocks?:
    | T
    | {
        block?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  isDefault?: T;
  permissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums_select".
 */
export interface GalleryAlbumsSelect<T extends boolean = true> {
  slug?: T;
  slugLock?: T;
  settings?:
    | T
    | {
        isNsfw?: T;
        category?: T;
        tags?: T;
        visibility?: T;
        allowedRoles?: T;
        allowedUsers?: T;
      };
  tracking?:
    | T
    | {
        views?: T;
        downloads?: T;
        likes?: T;
        dislikes?: T;
        comments?: T;
        shares?: T;
        totalImages?: T;
      };
  title?: T;
  content?: T;
  images?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  settings?:
    | T
    | {
        isNsfw?: T;
        'gallery-tags'?: T;
        visibility?: T;
        allowedRoles?: T;
        allowedUsers?: T;
      };
  exif?: T;
  blurhash?: T;
  tracking?:
    | T
    | {
        views?: T;
        downloads?: T;
        likes?: T;
        dislikes?: T;
        comments?: T;
        shares?: T;
      };
  alt?: T;
  caption?: T;
  albums?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-tags_select".
 */
export interface GalleryTagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories_select".
 */
export interface GalleryCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gardens_select".
 */
export interface GardensSelect<T extends boolean = true> {
  slug?: T;
  slugLock?: T;
  name?: T;
  featuredImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kits_select".
 */
export interface KitsSelect<T extends boolean = true> {
  full_title?: T;
  title?: T;
  kit_number?: T;
  year_released?: T;
  scalemates?: T;
  models?: T;
  manufacturer?: T;
  scale?: T;
  boxart?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scales_select".
 */
export interface ScalesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers_select".
 */
export interface ManufacturersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models-tags_select".
 */
export interface ModelsTagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  clockify_project?: T;
  model_meta?:
    | T
    | {
        featuredImage?: T;
        status?: T;
        completionDate?: T;
        kit?: T;
        tags?: T;
        videos?:
          | T
          | {
              title?: T;
              url?: T;
              id?: T;
            };
      };
  relatedResources?:
    | T
    | {
        relatedPosts?: T;
        relatedModels?: T;
      };
  buildLog?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  image?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  models?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  galleryAlbums?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  galleryImages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  galleryTags?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  galleryCategories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  gardens?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  kits?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  scales?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  manufacturers?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  modelsTags?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  posts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  postsCategories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  postsTags?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  mapMarkers?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  active?: T;
  lastUsed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets_select".
 */
export interface PayloadQueryPresetsSelect<T extends boolean = true> {
  title?: T;
  isShared?: T;
  access?:
    | T
    | {
        read?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        update?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        delete?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
      };
  where?: T;
  columns?: T;
  groupBy?: T;
  relatedCollection?: T;
  isTemp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-meta".
 */
export interface SiteMeta {
  id: number;
  siteMeta?:
    | {
        title: string;
        description: string;
        path: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation".
 */
export interface SiteNavigation {
  id: number;
  navItems?:
    | {
        title: string;
        link: string;
        childNodes?:
          | {
              title: string;
              link: string;
              order: number;
              icon?: (number | null) | Media;
              visibility: 'ALL' | 'AUTHENTICATED' | 'ANONYMOUS' | 'PRIVILEGED';
              allowedRoles?: (number | Role)[] | null;
              allowedUsers?: (number | User)[] | null;
              id?: string | null;
            }[]
          | null;
        order: number;
        icon?: (number | null) | Media;
        visibility: 'ALL' | 'AUTHENTICATED' | 'ANONYMOUS' | 'PRIVILEGED';
        allowedRoles?: (number | Role)[] | null;
        allowedUsers?: (number | User)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure which collections and CRUD operations should emit webhook events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhooks".
 */
export interface Webhook {
  id: number;
  /**
   * Configure webhook events for each collection.
   */
  collections?:
    | {
        /**
         * Select a collection
         */
        collection:
          | 'map-markers'
          | 'media'
          | 'posts'
          | 'posts-categories'
          | 'posts-tags'
          | 'pages'
          | 'roles'
          | 'gallery-albums'
          | 'gallery-images'
          | 'gallery-tags'
          | 'gallery-categories'
          | 'gardens'
          | 'kits'
          | 'scales'
          | 'manufacturers'
          | 'models-tags'
          | 'models'
          | 'payload-mcp-api-keys'
          | 'search';
        enabled?: boolean | null;
        /**
         * Select which CRUD operations should emit webhook events.
         */
        operations?: {
          create?: boolean | null;
          read?: boolean | null;
          update?: boolean | null;
          delete?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-meta_select".
 */
export interface SiteMetaSelect<T extends boolean = true> {
  siteMeta?:
    | T
    | {
        title?: T;
        description?: T;
        path?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation_select".
 */
export interface SiteNavigationSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        title?: T;
        link?: T;
        childNodes?:
          | T
          | {
              title?: T;
              link?: T;
              order?: T;
              icon?: T;
              visibility?: T;
              allowedRoles?: T;
              allowedUsers?: T;
              id?: T;
            };
        order?: T;
        icon?: T;
        visibility?: T;
        allowedRoles?: T;
        allowedUsers?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhooks_select".
 */
export interface WebhooksSelect<T extends boolean = true> {
  collections?:
    | T
    | {
        collection?: T;
        enabled?: T;
        operations?:
          | T
          | {
              create?: T;
              read?: T;
              update?: T;
              delete?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendWelcomeEmail".
 */
export interface TaskSendWelcomeEmail {
  input: {
    userEmail: string;
    userName: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateImageEXIF".
 */
export interface TaskGenerateImageEXIF {
  input: {
    imageId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}